// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents an address entity when updating addresses.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddressUpdate : IParsable
    {
        /// <summary>City of this address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_city? City { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_city City { get; set; }
#endif
        /// <summary>Supported two-letter ISO 3166-1 alpha-2 country code for this address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_country_code? CountryCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_country_code CountryCode { get; set; }
#endif
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_custom_data? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_custom_data CustomData { get; set; }
#endif
        /// <summary>Memorable description for this address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_description? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_description Description { get; set; }
#endif
        /// <summary>First line of this address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_first_line? FirstLine { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_first_line FirstLine { get; set; }
#endif
        /// <summary>ZIP or postal code of this address. Required for some countries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_postal_code? PostalCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_postal_code PostalCode { get; set; }
#endif
        /// <summary>State, county, or region of this address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_region? Region { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_region Region { get; set; }
#endif
        /// <summary>Second line of this address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_second_line? SecondLine { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_second_line SecondLine { get; set; }
#endif
        /// <summary>Whether this entity can be used in Paddle.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.Status? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "city", n => { City = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_city>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_city.CreateFromDiscriminatorValue); } },
                { "country_code", n => { CountryCode = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_country_code>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_country_code.CreateFromDiscriminatorValue); } },
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_custom_data>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_custom_data.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_description>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_description.CreateFromDiscriminatorValue); } },
                { "first_line", n => { FirstLine = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_first_line>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_first_line.CreateFromDiscriminatorValue); } },
                { "postal_code", n => { PostalCode = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_postal_code>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_postal_code.CreateFromDiscriminatorValue); } },
                { "region", n => { Region = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_region>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_region.CreateFromDiscriminatorValue); } },
                { "second_line", n => { SecondLine = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_second_line>(global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_second_line.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.Status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_city>("city", City);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_country_code>("country_code", CountryCode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_custom_data>("custom_data", CustomData);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_description>("description", Description);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_first_line>("first_line", FirstLine);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_postal_code>("postal_code", PostalCode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_region>("region", Region);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressUpdate_second_line>("second_line", SecondLine);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.Status>("status", Status);
        }
    }
}
#pragma warning restore CS0618
