// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents an adjustment entity when creating adjustments.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdjustmentCreate : IAdditionalDataHolder, IParsable
    {
        /// <summary>How this adjustment impacts the related transaction.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentAction? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of transaction items to adjust. Required if `type` is not populated or set to `partial`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentItemCreate>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentItemCreate> Items { get; set; }
#endif
        /// <summary>Why this adjustment was created. Appears in the Paddle dashboard. Retained for recordkeeping purposes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The tax_mode property</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentTaxMode? TaxMode { get; set; }
        /// <summary>Paddle ID of the transaction that this adjustment is for, prefixed with `txn_`.Automatically-collected transactions must be `completed`; manually-collected transactions must have a status of `billed` or `past_due`You can&apos;t create an adjustment for a transaction that has a refund that&apos;s pending approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId { get; set; }
#nullable restore
#else
        public string TransactionId { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentCreate"/> and sets the default values.
        /// </summary>
        public AdjustmentCreate()
        {
            AdditionalData = new Dictionary<string, object>();
            TaxMode = global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentTaxMode.Internal;
            Type = global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentType.Partial;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentAction>(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentItemCreate>(global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentItemCreate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "tax_mode", n => { TaxMode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentTaxMode>(); } },
                { "transaction_id", n => { TransactionId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentAction>("action", Action);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentItemCreate>("items", Items);
            writer.WriteStringValue("reason", Reason);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentTaxMode>("tax_mode", TaxMode);
            writer.WriteStringValue("transaction_id", TransactionId);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.AdjustmentType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
