// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>How this adjustment impacts the related transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdjustmentActionQuery
    {
        [EnumMember(Value = "credit")]
        #pragma warning disable CS1591
        Credit,
        #pragma warning restore CS1591
        [EnumMember(Value = "refund")]
        #pragma warning disable CS1591
        Refund,
        #pragma warning restore CS1591
        [EnumMember(Value = "chargeback")]
        #pragma warning disable CS1591
        Chargeback,
        #pragma warning restore CS1591
        [EnumMember(Value = "chargeback_reverse")]
        #pragma warning disable CS1591
        Chargeback_reverse,
        #pragma warning restore CS1591
        [EnumMember(Value = "chargeback_warning")]
        #pragma warning disable CS1591
        Chargeback_warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "chargeback_warning_reverse")]
        #pragma warning disable CS1591
        Chargeback_warning_reverse,
        #pragma warning restore CS1591
        [EnumMember(Value = "credit_reverse")]
        #pragma warning disable CS1591
        Credit_reverse,
        #pragma warning restore CS1591
    }
}
