// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>Action performed by Paddle as a result of this exposure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiKeyExposureCreatedRequestDataActionTaken
    {
        [EnumMember(Value = "revoked")]
        #pragma warning disable CS1591
        Revoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
