// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a business entity when creating businesses.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessCreate : IParsable
    {
        /// <summary>Company number for this business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_company_number? CompanyNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_company_number CompanyNumber { get; set; }
#endif
        /// <summary>List of contacts related to this business, typically used for sending invoices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_contacts? Contacts { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_contacts Contacts { get; set; }
#endif
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_custom_data? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_custom_data CustomData { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_id? Id { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_id Id { get; private set; }
#endif
        /// <summary>Import information for this entity. `null` if this entity is not imported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_import_meta? ImportMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_import_meta ImportMeta { get; set; }
#endif
        /// <summary>Name of this business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_name Name { get; set; }
#endif
        /// <summary>Tax or VAT Number for this business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_tax_identifier? TaxIdentifier { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_tax_identifier TaxIdentifier { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company_number", n => { CompanyNumber = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_company_number>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_company_number.CreateFromDiscriminatorValue); } },
                { "contacts", n => { Contacts = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_contacts>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_contacts.CreateFromDiscriminatorValue); } },
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_custom_data>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_custom_data.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_id>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_id.CreateFromDiscriminatorValue); } },
                { "import_meta", n => { ImportMeta = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_import_meta>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_import_meta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_name>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_name.CreateFromDiscriminatorValue); } },
                { "tax_identifier", n => { TaxIdentifier = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_tax_identifier>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_tax_identifier.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_company_number>("company_number", CompanyNumber);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_contacts>("contacts", Contacts);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_custom_data>("custom_data", CustomData);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_import_meta>("import_meta", ImportMeta);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_name>("name", Name);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate_tax_identifier>("tax_identifier", TaxIdentifier);
        }
    }
}
#pragma warning restore CS0618
