// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>Type of credit or debit card used to pay.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardType
    {
        [EnumMember(Value = "american_express")]
        #pragma warning disable CS1591
        American_express,
        #pragma warning restore CS1591
        [EnumMember(Value = "diners_club")]
        #pragma warning disable CS1591
        Diners_club,
        #pragma warning restore CS1591
        [EnumMember(Value = "discover")]
        #pragma warning disable CS1591
        Discover,
        #pragma warning restore CS1591
        [EnumMember(Value = "jcb")]
        #pragma warning disable CS1591
        Jcb,
        #pragma warning restore CS1591
        [EnumMember(Value = "mada")]
        #pragma warning disable CS1591
        Mada,
        #pragma warning restore CS1591
        [EnumMember(Value = "maestro")]
        #pragma warning disable CS1591
        Maestro,
        #pragma warning restore CS1591
        [EnumMember(Value = "mastercard")]
        #pragma warning disable CS1591
        Mastercard,
        #pragma warning restore CS1591
        [EnumMember(Value = "union_pay")]
        #pragma warning disable CS1591
        Union_pay,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "visa")]
        #pragma warning disable CS1591
        Visa,
        #pragma warning restore CS1591
    }
}
