// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a customer payment method entity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerPaymentMethod : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unique Paddle ID for this address entity, prefixed with `add_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressId { get; set; }
#nullable restore
#else
        public string AddressId { get; set; }
#endif
        /// <summary>Information about the credit or debit card saved. `null` unless `type` is `card`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.Card? Card { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.Card Card { get; private set; }
#endif
        /// <summary>Unique Paddle ID for this customer entity, prefixed with `ctm_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Unique Paddle ID for this payment method entity, prefixed with `paymtd_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Describes how this payment method was saved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodOriginComposed? Origin { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodOriginComposed Origin { get; private set; }
#endif
        /// <summary>Information about the PayPal payment method saved. `null` unless `type` is `paypal`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.Paypal? Paypal { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.Paypal Paypal { get; private set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was saved. Set automatically by Paddle.</summary>
        public DateTimeOffset? SavedAt { get; set; }
        /// <summary>Information about the Korean payment method used to pay. `null` unless `type` is `south_korea_local_card`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SouthKoreaLocalCard? SouthKoreaLocalCard { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SouthKoreaLocalCard SouthKoreaLocalCard { get; private set; }
#endif
        /// <summary>Type of payment method saved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodTypeComposed? Type { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodTypeComposed Type { get; private set; }
#endif
        /// <summary>The underlying_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.UnderlyingDetails? UnderlyingDetails { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.UnderlyingDetails UnderlyingDetails { get; private set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethod"/> and sets the default values.
        /// </summary>
        public CustomerPaymentMethod()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethod"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethod CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethod();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_id", n => { AddressId = n.GetStringValue(); } },
                { "card", n => { Card = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.Card>(global::Soenneker.Paddle.OpenApiClient.Models.Card.CreateFromDiscriminatorValue); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "origin", n => { Origin = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodOriginComposed>(global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodOriginComposed.CreateFromDiscriminatorValue); } },
                { "paypal", n => { Paypal = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.Paypal>(global::Soenneker.Paddle.OpenApiClient.Models.Paypal.CreateFromDiscriminatorValue); } },
                { "saved_at", n => { SavedAt = n.GetDateTimeOffsetValue(); } },
                { "south_korea_local_card", n => { SouthKoreaLocalCard = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SouthKoreaLocalCard>(global::Soenneker.Paddle.OpenApiClient.Models.SouthKoreaLocalCard.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodTypeComposed>(global::Soenneker.Paddle.OpenApiClient.Models.CustomerPaymentMethodTypeComposed.CreateFromDiscriminatorValue); } },
                { "underlying_details", n => { UnderlyingDetails = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.UnderlyingDetails>(global::Soenneker.Paddle.OpenApiClient.Models.UnderlyingDetails.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address_id", AddressId);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("saved_at", SavedAt);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
