// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a discount entity when updating discounts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiscountUpdate : IParsable
    {
        /// <summary>Amount to discount by. For `percentage` discounts, must be an amount between `0.01` and `100`. For `flat` and `flat_per_seat` discounts, amount in the lowest denomination for a currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Amount { get; set; }
#nullable restore
#else
        public string Amount { get; set; }
#endif
        /// <summary>Unique code that customers can use to redeem this discount at checkout. Not case-sensitive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountCode? Code { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountCode Code { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>Supported three-letter ISO 4217 currency code. Required where discount type is `flat` or `flat_per_seat`.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCode? CurrencyCode { get; set; }
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomData? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomData CustomData { get; set; }
#endif
        /// <summary>Short description for this discount for your reference. Not shown to customers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Paddle ID for the discount group related to this discount, prefixed with `dsg_`. `null` if not in a discount group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountGroupId? DiscountGroupId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountGroupId DiscountGroupId { get; set; }
#endif
        /// <summary>Whether this discount can be redeemed by customers at checkout (`true`) or not (`false`).</summary>
        public bool? EnabledForCheckout { get; set; }
        /// <summary>RFC 3339 datetime string of when this discount expires. Discount can no longer be redeemed after this date has elapsed. `null` if this discount can be redeemed forever.Expired discounts can&apos;t be redeemed against transactions or checkouts, but can be applied when updating subscriptions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.Timestamp? ExpiresAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.Timestamp ExpiresAt { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>Import information for this entity. `null` if this entity is not imported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta? ImportMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta ImportMeta { get; set; }
#endif
        /// <summary>Number of subscription billing periods that this discount recurs for. Requires `recur`. `null` if this discount recurs forever.Subscription renewals, midcycle changes, and one-time charges billed to a subscription aren&apos;t considered a redemption. `times_used` is not incremented in these cases.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals? MaximumRecurringIntervals { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals MaximumRecurringIntervals { get; set; }
#endif
        /// <summary>Discount mode. Standard discounts are considered part of your catalog and are shown in the Paddle dashboard.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountMode? Mode { get; set; }
        /// <summary>Whether this discount applies for multiple subscription billing periods (`true`) or not (`false`).</summary>
        public bool? Recur { get; set; }
        /// <summary>Product or price IDs that this discount is for. When including a product ID, all prices for that product can be discounted. `null` if this discount applies to all products and prices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.DiscountRestrictTo>? RestrictTo { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.DiscountRestrictTo> RestrictTo { get; set; }
#endif
        /// <summary>Whether this entity can be used in Paddle.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountStatus? Status { get; set; }
        /// <summary>How many times this discount has been redeemed. Automatically incremented by Paddle.Paddle counts a usage as a redemption on a checkout, transaction, or subscription. Transactions created for subscription renewals, midcycle changes, and one-time charges aren&apos;t considered a redemption.</summary>
        public int? TimesUsed { get; private set; }
        /// <summary>Type of discount. Determines how this discount impacts the checkout or transaction total.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountType? Type { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>Maximum number of times this discount can be redeemed. This is an overall limit for this discount, rather than a per-customer limit. `null` if this discount can be redeemed an unlimited amount of times.Paddle counts a usage as a redemption on a checkout, transaction, or the initial application against a subscription. Transactions created for subscription renewals, midcycle changes, and one-time charges aren&apos;t considered a redemption.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit? UsageLimit { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit UsageLimit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate"/> and sets the default values.
        /// </summary>
        public DiscountUpdate()
        {
            Mode = global::Soenneker.Paddle.OpenApiClient.Models.DiscountMode.Standard;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetStringValue(); } },
                { "code", n => { Code = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountCode>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountCode.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency_code", n => { CurrencyCode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCode>(); } },
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomData>(global::Soenneker.Paddle.OpenApiClient.Models.CustomData.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "discount_group_id", n => { DiscountGroupId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountGroupId>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountGroupId.CreateFromDiscriminatorValue); } },
                { "enabled_for_checkout", n => { EnabledForCheckout = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.Timestamp>(global::Soenneker.Paddle.OpenApiClient.Models.Timestamp.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "import_meta", n => { ImportMeta = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta>(global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta.CreateFromDiscriminatorValue); } },
                { "maximum_recurring_intervals", n => { MaximumRecurringIntervals = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals.CreateFromDiscriminatorValue); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountMode>(); } },
                { "recur", n => { Recur = n.GetBoolValue(); } },
                { "restrict_to", n => { RestrictTo = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.DiscountRestrictTo>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountRestrictTo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountStatus>(); } },
                { "times_used", n => { TimesUsed = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "usage_limit", n => { UsageLimit = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("amount", Amount);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountCode>("code", Code);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCode>("currency_code", CurrencyCode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomData>("custom_data", CustomData);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountGroupId>("discount_group_id", DiscountGroupId);
            writer.WriteBoolValue("enabled_for_checkout", EnabledForCheckout);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.Timestamp>("expires_at", ExpiresAt);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta>("import_meta", ImportMeta);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals>("maximum_recurring_intervals", MaximumRecurringIntervals);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountMode>("mode", Mode);
            writer.WriteBoolValue("recur", Recur);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.DiscountRestrictTo>("restrict_to", RestrictTo);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit>("usage_limit", UsageLimit);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_maximum_recurring_intervalsMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountUpdate_maximum_recurring_intervals : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_maximum_recurring_intervalsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_maximum_recurring_intervalsMember1? DiscountUpdateMaximumRecurringIntervalsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_maximum_recurring_intervalsMember1 DiscountUpdateMaximumRecurringIntervalsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_maximum_recurring_intervals();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.DiscountUpdateMaximumRecurringIntervalsMember1 = new global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_maximum_recurring_intervalsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountUpdateMaximumRecurringIntervalsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountUpdateMaximumRecurringIntervalsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_maximum_recurring_intervalsMember1>(null, DiscountUpdateMaximumRecurringIntervalsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_usage_limitMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DiscountUpdate_usage_limit : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_usage_limitMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_usage_limitMember1? DiscountUpdateUsageLimitMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_usage_limitMember1 DiscountUpdateUsageLimitMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate.DiscountUpdate_usage_limit();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.DiscountUpdateUsageLimitMember1 = new global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_usage_limitMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DiscountUpdateUsageLimitMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DiscountUpdateUsageLimitMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate_usage_limitMember1>(null, DiscountUpdateUsageLimitMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
