// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>Type of event sent by Paddle, in the format `entity.event_type`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventTypeName
    {
        [EnumMember(Value = "address.created")]
        #pragma warning disable CS1591
        AddressCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "address.imported")]
        #pragma warning disable CS1591
        AddressImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "address.updated")]
        #pragma warning disable CS1591
        AddressUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "adjustment.created")]
        #pragma warning disable CS1591
        AdjustmentCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "adjustment.updated")]
        #pragma warning disable CS1591
        AdjustmentUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.created")]
        #pragma warning disable CS1591
        Api_keyCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.expired")]
        #pragma warning disable CS1591
        Api_keyExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.expiring")]
        #pragma warning disable CS1591
        Api_keyExpiring,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.revoked")]
        #pragma warning disable CS1591
        Api_keyRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.updated")]
        #pragma warning disable CS1591
        Api_keyUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key_exposure.created")]
        #pragma warning disable CS1591
        Api_key_exposureCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "business.created")]
        #pragma warning disable CS1591
        BusinessCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "business.imported")]
        #pragma warning disable CS1591
        BusinessImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "business.updated")]
        #pragma warning disable CS1591
        BusinessUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "client_token.created")]
        #pragma warning disable CS1591
        Client_tokenCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "client_token.revoked")]
        #pragma warning disable CS1591
        Client_tokenRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "client_token.updated")]
        #pragma warning disable CS1591
        Client_tokenUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "customer.created")]
        #pragma warning disable CS1591
        CustomerCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "customer.imported")]
        #pragma warning disable CS1591
        CustomerImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "customer.updated")]
        #pragma warning disable CS1591
        CustomerUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount.created")]
        #pragma warning disable CS1591
        DiscountCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount.imported")]
        #pragma warning disable CS1591
        DiscountImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount.updated")]
        #pragma warning disable CS1591
        DiscountUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount_group.created")]
        #pragma warning disable CS1591
        Discount_groupCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount_group.updated")]
        #pragma warning disable CS1591
        Discount_groupUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_method.saved")]
        #pragma warning disable CS1591
        Payment_methodSaved,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_method.deleted")]
        #pragma warning disable CS1591
        Payment_methodDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "payout.created")]
        #pragma warning disable CS1591
        PayoutCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "payout.paid")]
        #pragma warning disable CS1591
        PayoutPaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "price.created")]
        #pragma warning disable CS1591
        PriceCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "price.imported")]
        #pragma warning disable CS1591
        PriceImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "price.updated")]
        #pragma warning disable CS1591
        PriceUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "product.created")]
        #pragma warning disable CS1591
        ProductCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "product.imported")]
        #pragma warning disable CS1591
        ProductImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "product.updated")]
        #pragma warning disable CS1591
        ProductUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "report.created")]
        #pragma warning disable CS1591
        ReportCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "report.updated")]
        #pragma warning disable CS1591
        ReportUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.activated")]
        #pragma warning disable CS1591
        SubscriptionActivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.canceled")]
        #pragma warning disable CS1591
        SubscriptionCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.created")]
        #pragma warning disable CS1591
        SubscriptionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.imported")]
        #pragma warning disable CS1591
        SubscriptionImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.past_due")]
        #pragma warning disable CS1591
        SubscriptionPast_due,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.paused")]
        #pragma warning disable CS1591
        SubscriptionPaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.resumed")]
        #pragma warning disable CS1591
        SubscriptionResumed,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.trialing")]
        #pragma warning disable CS1591
        SubscriptionTrialing,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription.updated")]
        #pragma warning disable CS1591
        SubscriptionUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.billed")]
        #pragma warning disable CS1591
        TransactionBilled,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.canceled")]
        #pragma warning disable CS1591
        TransactionCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.completed")]
        #pragma warning disable CS1591
        TransactionCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.created")]
        #pragma warning disable CS1591
        TransactionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.paid")]
        #pragma warning disable CS1591
        TransactionPaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.past_due")]
        #pragma warning disable CS1591
        TransactionPast_due,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.payment_failed")]
        #pragma warning disable CS1591
        TransactionPayment_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.ready")]
        #pragma warning disable CS1591
        TransactionReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.revised")]
        #pragma warning disable CS1591
        TransactionRevised,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.updated")]
        #pragma warning disable CS1591
        TransactionUpdated,
        #pragma warning restore CS1591
    }
}
