// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Revenue metrics timeseries with amount and transaction count for each datapoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetricsTimeseriesRevenue : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Supported three-letter ISO 4217 currency code for this metric. Returned in your primary balance currency, converted using the current exchange rate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueCurrencyCode? CurrencyCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueCurrencyCode CurrencyCode { get; set; }
#endif
        /// <summary>RFC 3339 datetime string.</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>Granularity for this timeseries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueInterval? Interval { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueInterval Interval { get; set; }
#endif
        /// <summary>RFC 3339 datetime string.</summary>
        public DateTimeOffset? StartsAt { get; set; }
        /// <summary>Array of datapoints. Empty if `to` and `from` are the same.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueDatapoint>? Timeseries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueDatapoint> Timeseries { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenue"/> and sets the default values.
        /// </summary>
        public MetricsTimeseriesRevenue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency_code", n => { CurrencyCode = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueCurrencyCode>(global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueCurrencyCode.CreateFromDiscriminatorValue); } },
                { "ends_at", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "interval", n => { Interval = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueInterval>(global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueInterval.CreateFromDiscriminatorValue); } },
                { "starts_at", n => { StartsAt = n.GetDateTimeOffsetValue(); } },
                { "timeseries", n => { Timeseries = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueDatapoint>(global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueDatapoint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueCurrencyCode>("currency_code", CurrencyCode);
            writer.WriteDateTimeOffsetValue("ends_at", EndsAt);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueInterval>("interval", Interval);
            writer.WriteDateTimeOffsetValue("starts_at", StartsAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.MetricsTimeseriesRevenueDatapoint>("timeseries", Timeseries);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
