// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NotificationStatusQueryEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "needs_retry")]
        #pragma warning disable CS1591
        Needs_retry,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_attempted")]
        #pragma warning disable CS1591
        Not_attempted,
        #pragma warning restore CS1591
    }
}
