// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PriceIncludeEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
    }
}
