// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a product entity when creating products.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductCreate : IParsable
    {
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomData? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomData CustomData { get; set; }
#endif
        /// <summary>Short description for this product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Image for this product. Included in the checkout and on some customer documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url? ImageUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url ImageUrl { get; set; }
#endif
        /// <summary>Import information for this entity. `null` if this entity is not imported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta? ImportMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta ImportMeta { get; set; }
#endif
        /// <summary>Name of this product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Tax category for this product. Used for charging the correct rate of tax. Selected tax category must be enabled on your Paddle account.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.TaxCategory? TaxCategory { get; set; }
        /// <summary>Type of item. Standard items are considered part of your catalog and are shown in the Paddle dashboard. If omitted, defaults to `standard`.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.CatalogType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate"/> and sets the default values.
        /// </summary>
        public ProductCreate()
        {
            Type = global::Soenneker.Paddle.OpenApiClient.Models.CatalogType.Standard;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomData>(global::Soenneker.Paddle.OpenApiClient.Models.CustomData.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description>(global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image_url", n => { ImageUrl = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url>(global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url.CreateFromDiscriminatorValue); } },
                { "import_meta", n => { ImportMeta = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta>(global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "tax_category", n => { TaxCategory = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TaxCategory>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CatalogType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomData>("custom_data", CustomData);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description>("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url>("image_url", ImageUrl);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ImportMeta>("import_meta", ImportMeta);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TaxCategory>("tax_category", TaxCategory);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CatalogType>("type", Type);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_descriptionMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductCreate_description : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_descriptionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_descriptionMember1? ProductCreateDescriptionMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_descriptionMember1 ProductCreateDescriptionMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_description();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ProductCreateDescriptionMember1 = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_descriptionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProductCreateDescriptionMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProductCreateDescriptionMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_descriptionMember1>(null, ProductCreateDescriptionMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.EmptyString"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ImageUrl"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_image_urlMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductCreate_image_url : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.EmptyString"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.EmptyString? EmptyString { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.EmptyString EmptyString { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ImageUrl"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.ImageUrl? ImageUrl { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.ImageUrl ImageUrl { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_image_urlMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_image_urlMember1? ProductCreateImageUrlMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_image_urlMember1 ProductCreateImageUrlMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate.ProductCreate_image_url();
                result.EmptyString = new global::Soenneker.Paddle.OpenApiClient.Models.EmptyString();
                result.ImageUrl = new global::Soenneker.Paddle.OpenApiClient.Models.ImageUrl();
                result.ProductCreateImageUrlMember1 = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreate_image_urlMember1();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(EmptyString != null || ImageUrl != null || ProductCreateImageUrlMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EmptyString, ImageUrl, ProductCreateImageUrlMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.EmptyString>(null, EmptyString, ImageUrl, ProductCreateImageUrlMember1);
            }
        }
    }
}
#pragma warning restore CS0618
