// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch1"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch3"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductCreateImageUrl : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch1? ProductCreateImageUrlBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch1 ProductCreateImageUrlBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch3? ProductCreateImageUrlBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch3 ProductCreateImageUrlBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlMember1? ProductCreateImageUrlMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlMember1 ProductCreateImageUrlMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrl"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrl CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrl();
            result.ProductCreateImageUrlBranch1 = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch1();
            result.ProductCreateImageUrlBranch3 = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch3();
            result.ProductCreateImageUrlMember1 = new global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlMember1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ProductCreateImageUrlBranch1 != null || ProductCreateImageUrlBranch3 != null || ProductCreateImageUrlMember1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProductCreateImageUrlBranch1, ProductCreateImageUrlBranch3, ProductCreateImageUrlMember1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.ProductCreateImageUrlBranch1>(null, ProductCreateImageUrlBranch1, ProductCreateImageUrlBranch3, ProductCreateImageUrlMember1);
        }
    }
}
#pragma warning restore CS0618
