// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>Type of report.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReportTypeCheckouts
    {
        [EnumMember(Value = "checkouts")]
        #pragma warning disable CS1591
        Checkouts,
        #pragma warning restore CS1591
    }
}
