// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ScheduledChangeActionQuery
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cancel")]
        #pragma warning disable CS1591
        Cancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause")]
        #pragma warning disable CS1591
        Pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "resume")]
        #pragma warning disable CS1591
        Resume,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
