// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Configuration for this scenario simulation. Determines which granular flow is simulated and what entities are used to populate webhook payloads with.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SimulationScenarioEventsModelConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The subscription_cancellation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCancellation? SubscriptionCancellation { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCancellation SubscriptionCancellation { get; set; }
#endif
        /// <summary>The subscription_creation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCreation? SubscriptionCreation { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCreation SubscriptionCreation { get; set; }
#endif
        /// <summary>The subscription_pause property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionPause? SubscriptionPause { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionPause SubscriptionPause { get; set; }
#endif
        /// <summary>The subscription_renewal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionRenewal? SubscriptionRenewal { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionRenewal SubscriptionRenewal { get; set; }
#endif
        /// <summary>The subscription_resume property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionResume? SubscriptionResume { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionResume SubscriptionResume { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioEventsModelConfig"/> and sets the default values.
        /// </summary>
        public SimulationScenarioEventsModelConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioEventsModelConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioEventsModelConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioEventsModelConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "subscription_cancellation", n => { SubscriptionCancellation = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCancellation>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCancellation.CreateFromDiscriminatorValue); } },
                { "subscription_creation", n => { SubscriptionCreation = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCreation>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCreation.CreateFromDiscriminatorValue); } },
                { "subscription_pause", n => { SubscriptionPause = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionPause>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionPause.CreateFromDiscriminatorValue); } },
                { "subscription_renewal", n => { SubscriptionRenewal = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionRenewal>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionRenewal.CreateFromDiscriminatorValue); } },
                { "subscription_resume", n => { SubscriptionResume = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionResume>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionResume.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCancellation>("subscription_cancellation", SubscriptionCancellation);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionCreation>("subscription_creation", SubscriptionCreation);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionPause>("subscription_pause", SubscriptionPause);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionRenewal>("subscription_renewal", SubscriptionRenewal);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationScenarioConfigSubscriptionResume>("subscription_resume", SubscriptionResume);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
