// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Options that determine which webhooks are sent as part of a simulation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SimulationConfigSubscriptionCreationOptionsComposed : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Determines which webhooks are sent based on whether a new, existing, or no business was provided. If omitted, defaults to `not_provided`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsBusinessSimulatedAsComposed? BusinessSimulatedAs { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsBusinessSimulatedAsComposed BusinessSimulatedAs { get; set; }
#endif
        /// <summary>Determines which webhooks are sent based on whether a new or existing customer subscribes, and how their details are entered if they&apos;re an existing customer. If omitted, defaults to `new`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsCustomerSimulatedAsComposed? CustomerSimulatedAs { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsCustomerSimulatedAsComposed CustomerSimulatedAs { get; set; }
#endif
        /// <summary>Determines which webhooks are sent based on whether a discount is used and how it&apos;s entered. If omitted, defaults to `not_provided`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsDiscountSimulatedAsComposed? DiscountSimulatedAs { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsDiscountSimulatedAsComposed DiscountSimulatedAs { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsComposed"/> and sets the default values.
        /// </summary>
        public SimulationConfigSubscriptionCreationOptionsComposed()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsComposed"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsComposed CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsComposed();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "business_simulated_as", n => { BusinessSimulatedAs = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsBusinessSimulatedAsComposed>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsBusinessSimulatedAsComposed.CreateFromDiscriminatorValue); } },
                { "customer_simulated_as", n => { CustomerSimulatedAs = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsCustomerSimulatedAsComposed>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsCustomerSimulatedAsComposed.CreateFromDiscriminatorValue); } },
                { "discount_simulated_as", n => { DiscountSimulatedAs = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsDiscountSimulatedAsComposed>(global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsDiscountSimulatedAsComposed.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsBusinessSimulatedAsComposed>("business_simulated_as", BusinessSimulatedAs);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsCustomerSimulatedAsComposed>("customer_simulated_as", CustomerSimulatedAs);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigSubscriptionCreationOptionsDiscountSimulatedAsComposed>("discount_simulated_as", DiscountSimulatedAs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
