// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SimulationConfigSubscriptionCreationOptionsCustomerSimulatedAs
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        NewValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "existing_email_matched")]
        #pragma warning disable CS1591
        ExistingEmailMatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "existing_details_prefilled")]
        #pragma warning disable CS1591
        ExistingDetailsPrefilled,
        #pragma warning restore CS1591
    }
}
