// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SimulationConfigOptionsPaymentRecoveredExistingPaymentOutcome
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "recovered_existing_payment_method")]
        #pragma warning disable CS1591
        Recovered_existing_payment_method,
        #pragma warning restore CS1591
    }
}
