// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunScenarioModel"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunSingleEventModel"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SimulationRun : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunScenarioModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunScenarioModel? SimulationRunScenarioModel { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunScenarioModel SimulationRunScenarioModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunSingleEventModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunSingleEventModel? SimulationRunSingleEventModel { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunSingleEventModel SimulationRunSingleEventModel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationRun"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SimulationRun CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Paddle.OpenApiClient.Models.SimulationRun();
            if("SimulationRunScenarioModel".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SimulationRunScenarioModel = new global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunScenarioModel();
            }
            else if("SimulationRunSingleEventModel".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SimulationRunSingleEventModel = new global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunSingleEventModel();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SimulationRunScenarioModel != null)
            {
                return SimulationRunScenarioModel.GetFieldDeserializers();
            }
            else if(SimulationRunSingleEventModel != null)
            {
                return SimulationRunSingleEventModel.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SimulationRunScenarioModel != null)
            {
                writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunScenarioModel>(null, SimulationRunScenarioModel);
            }
            else if(SimulationRunSingleEventModel != null)
            {
                writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SimulationRunSingleEventModel>(null, SimulationRunSingleEventModel);
            }
        }
    }
}
#pragma warning restore CS0618
