// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Configuration resources for subscription creation simulations with existing transaction
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SimulationConfigEntitiesSubscriptionCreationTransaction : IParsable
    {
        /// <summary>Paddle ID of an address. Adds address details to webhook payloads. Requires `customer_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressId? AddressId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressId AddressId { get; set; }
#endif
        /// <summary>Paddle ID of a business. Adds business details to webhook payloads. Requires `customer_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessId? BusinessId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessId BusinessId { get; set; }
#endif
        /// <summary>Paddle ID of a customer. Adds customer details to webhook payloads.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerId? CustomerId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerId CustomerId { get; set; }
#endif
        /// <summary>Paddle ID of a discount. Adds discount details (including price calculations) to webhook payloads. Requires `items` or `transaction_id` for the discount to be applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountId? DiscountId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountId DiscountId { get; set; }
#endif
        /// <summary>Items to include on the simulated subscription. Only existing products and prices can be simulated. Non-catalog items aren&apos;t supported. At least one recurring price must be provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Items { get; set; }
#nullable restore
#else
        public UntypedNode Items { get; set; }
#endif
        /// <summary>Paddle ID of a payment method. Adds payment method details to webhook payloads. Requires `customer_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodId? PaymentMethodId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodId PaymentMethodId { get; set; }
#endif
        /// <summary>Paddle ID of a transaction. Bases the subscription from this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId { get; set; }
#nullable restore
#else
        public string TransactionId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigEntitiesSubscriptionCreationTransaction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigEntitiesSubscriptionCreationTransaction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.SimulationConfigEntitiesSubscriptionCreationTransaction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_id", n => { AddressId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressId>(global::Soenneker.Paddle.OpenApiClient.Models.AddressId.CreateFromDiscriminatorValue); } },
                { "business_id", n => { BusinessId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessId>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessId.CreateFromDiscriminatorValue); } },
                { "customer_id", n => { CustomerId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomerId>(global::Soenneker.Paddle.OpenApiClient.Models.CustomerId.CreateFromDiscriminatorValue); } },
                { "discount_id", n => { DiscountId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountId>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountId.CreateFromDiscriminatorValue); } },
                { "items", n => { Items = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "payment_method_id", n => { PaymentMethodId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodId>(global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodId.CreateFromDiscriminatorValue); } },
                { "transaction_id", n => { TransactionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressId>("address_id", AddressId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessId>("business_id", BusinessId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomerId>("customer_id", CustomerId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountId>("discount_id", DiscountId);
            writer.WriteObjectValue<UntypedNode>("items", Items);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodId>("payment_method_id", PaymentMethodId);
            writer.WriteStringValue("transaction_id", TransactionId);
        }
    }
}
#pragma warning restore CS0618
