// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a specific condition under which explicit customer consent is, or was, mandated for a subscription renewal.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubscriptionConsentRequirement : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Period during which consent for this subscription can be granted. `null` if there is no `next_billed_at` or the consent requirement does not apply to the current billing period.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TimePeriod? ConsentPeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TimePeriod ConsentPeriod { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>RFC 3339 datetime string of when the customer granted their consent. `null` if not yet granted.</summary>
        public DateTimeOffset? GrantedAt { get; set; }
        /// <summary>Unique Paddle ID for this subscription consent requirement entity, prefixed with `subconreq_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Type of consent required for successful renewal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementRequirement? Requirement { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementRequirement Requirement { get; set; }
#endif
        /// <summary>Status of this consent requirement.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementStatusComposed? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementStatusComposed Status { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when consent was voided or no longer required. `null` if not voided.</summary>
        public DateTimeOffset? VoidedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirement"/> and sets the default values.
        /// </summary>
        public SubscriptionConsentRequirement()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "consent_period", n => { ConsentPeriod = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TimePeriod>(global::Soenneker.Paddle.OpenApiClient.Models.TimePeriod.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "granted_at", n => { GrantedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "requirement", n => { Requirement = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementRequirement>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementRequirement.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementStatusComposed>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementStatusComposed.CreateFromDiscriminatorValue); } },
                { "voided_at", n => { VoidedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TimePeriod>("consent_period", ConsentPeriod);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("granted_at", GrantedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementRequirement>("requirement", Requirement);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionConsentRequirementStatusComposed>("status", Status);
            writer.WriteDateTimeOffsetValue("voided_at", VoidedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
