// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Related price entity for this item. This reflects the price entity at the time it was added to the subscription.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubscriptionUpdatedRequestDataItemsItemPrice : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>How often this price should be charged. `null` if price is non-recurring (one-time).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceBillingCycle? BillingCycle { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceBillingCycle BillingCycle { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceCustomData? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceCustomData CustomData { get; set; }
#endif
        /// <summary>Internal description for this price, not shown to customers. Typically notes for your team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Unique Paddle ID for this price, prefixed with `pri_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Import information for this entity. `null` if this entity is not imported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceImportMeta? ImportMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceImportMeta ImportMeta { get; set; }
#endif
        /// <summary>Name of this price, shown to customers at checkout and on invoices. Typically describes how often the related product bills.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Paddle ID for the product that this price is for, prefixed with `pro_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>Limits on how many times the related product can be purchased at this price. Useful for discount campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceQuantity? Quantity { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceQuantity Quantity { get; set; }
#endif
        /// <summary>Whether this entity can be used in Paddle.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceStatus? Status { get; set; }
        /// <summary>How tax is calculated for this price.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTaxMode? TaxMode { get; set; }
        /// <summary>Trial period for the product related to this price. The billing cycle begins once the trial period is over. `null` for no trial period. Requires `billing_cycle`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTrialPeriod? TrialPeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTrialPeriod TrialPeriod { get; set; }
#endif
        /// <summary>Type of item. Standard items are considered part of your catalog and are shown in the Paddle dashboard.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceType? Type { get; set; }
        /// <summary>Base price. This price applies to all customers, except for customers located in countries where you have `unit_price_overrides`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPrice? UnitPrice { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPrice UnitPrice { get; set; }
#endif
        /// <summary>List of unit price overrides. Use to override the base price with a custom price and currency for a country or group of countries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPriceOverridesItem>? UnitPriceOverrides { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPriceOverridesItem> UnitPriceOverrides { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPrice"/> and sets the default values.
        /// </summary>
        public SubscriptionUpdatedRequestDataItemsItemPrice()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPrice"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPrice CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPrice();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_cycle", n => { BillingCycle = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceBillingCycle>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceBillingCycle.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceCustomData>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceCustomData.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "import_meta", n => { ImportMeta = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceImportMeta>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceImportMeta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "product_id", n => { ProductId = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceQuantity>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceQuantity.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceStatus>(); } },
                { "tax_mode", n => { TaxMode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTaxMode>(); } },
                { "trial_period", n => { TrialPeriod = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTrialPeriod>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTrialPeriod.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceType>(); } },
                { "unit_price", n => { UnitPrice = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPrice>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPrice.CreateFromDiscriminatorValue); } },
                { "unit_price_overrides", n => { UnitPriceOverrides = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPriceOverridesItem>(global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPriceOverridesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceBillingCycle>("billing_cycle", BillingCycle);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceCustomData>("custom_data", CustomData);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceImportMeta>("import_meta", ImportMeta);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("product_id", ProductId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceQuantity>("quantity", Quantity);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTaxMode>("tax_mode", TaxMode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceTrialPeriod>("trial_period", TrialPeriod);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPrice>("unit_price", UnitPrice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionUpdatedRequestDataItemsItemPriceUnitPriceOverridesItem>("unit_price_overrides", UnitPriceOverrides);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
