// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>Whether this discount applies for multiple billing periods.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionPausedRequestDataDiscountType
    {
        [EnumMember(Value = "recurring")]
        #pragma warning disable CS1591
        Recurring,
        #pragma warning restore CS1591
        [EnumMember(Value = "one-off")]
        #pragma warning disable CS1591
        OneOff,
        #pragma warning restore CS1591
    }
}
