// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Change that&apos;s scheduled to be applied to a subscription. Use the pause subscription, cancel subscription, and resume subscription operations to create scheduled changes. `null` if no scheduled changes.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubscriptionCanceledRequestDataScheduledChange : IAdditionalDataHolder, IParsable
    {
        /// <summary>Kind of change that&apos;s scheduled to be applied to this subscription.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChangeAction? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>RFC 3339 datetime string of when this scheduled change takes effect.</summary>
        public DateTimeOffset? EffectiveAt { get; set; }
        /// <summary>RFC 3339 datetime string of when a paused subscription should resume. Only used for `pause` scheduled changes.</summary>
        public DateTimeOffset? ResumeAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChange"/> and sets the default values.
        /// </summary>
        public SubscriptionCanceledRequestDataScheduledChange()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChange"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChange CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChange();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChangeAction>(); } },
                { "effective_at", n => { EffectiveAt = n.GetDateTimeOffsetValue(); } },
                { "resume_at", n => { ResumeAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.SubscriptionCanceledRequestDataScheduledChangeAction>("action", Action);
            writer.WriteDateTimeOffsetValue("effective_at", EffectiveAt);
            writer.WriteDateTimeOffsetValue("resume_at", ResumeAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
