// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SubscriptionHistoryActorTypeQuery
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key")]
        #pragma warning disable CS1591
        ApiKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "paddle_staff")]
        #pragma warning disable CS1591
        PaddleStaff,
        #pragma warning restore CS1591
        [EnumMember(Value = "publisher")]
        #pragma warning disable CS1591
        Publisher,
        #pragma warning restore CS1591
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
    }
}
