// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>How tax is calculated for this price.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransactionCreatedRequestDataItemsItemPriceTaxMode
    {
        [EnumMember(Value = "account_setting")]
        #pragma warning disable CS1591
        AccountSetting,
        #pragma warning restore CS1591
        [EnumMember(Value = "external")]
        #pragma warning disable CS1591
        External,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal")]
        #pragma warning disable CS1591
        InternalValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "location")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
    }
}
