// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionPricingPreviewResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Address for this preview. Send one of `address_id`, `customer_ip_address`, or the `address` object when previewing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview Address { get; set; }
#endif
        /// <summary>Paddle ID of the address that this preview is for, prefixed with `add_`. Send one of `address_id`, `customer_ip_address`, or the `address` object when previewing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressId { get; set; }
#nullable restore
#else
        public string AddressId { get; set; }
#endif
        /// <summary>The available_payment_methods property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodType?>? AvailablePaymentMethods { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodType?> AvailablePaymentMethods { get; private set; }
#endif
        /// <summary>Paddle ID of the business that this preview is for, prefixed with `biz_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessId { get; set; }
#nullable restore
#else
        public string BusinessId { get; set; }
#endif
        /// <summary>Supported three-letter ISO 4217 currency code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodeWrapper15? CurrencyCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodeWrapper15 CurrencyCode { get; set; }
#endif
        /// <summary>Paddle ID of the customer that this preview is for, prefixed with `ctm_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>IP address for this transaction preview. Send one of `address_id`, `customer_ip_address`, or the `address` object when previewing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerIpAddress { get; set; }
#nullable restore
#else
        public string CustomerIpAddress { get; set; }
#endif
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponseDetails? Details { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponseDetails Details { get; private set; }
#endif
        /// <summary>Paddle ID of the discount applied to this preview, prefixed with `dsc_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscountId { get; set; }
#nullable restore
#else
        public string DiscountId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponse"/> and sets the default values.
        /// </summary>
        public TransactionPricingPreviewResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview>(global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview.CreateFromDiscriminatorValue); } },
                { "address_id", n => { AddressId = n.GetStringValue(); } },
                { "available_payment_methods", n => { AvailablePaymentMethods = n.GetCollectionOfEnumValues<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodType>()?.AsList(); } },
                { "business_id", n => { BusinessId = n.GetStringValue(); } },
                { "currency_code", n => { CurrencyCode = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodeWrapper15>(global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodeWrapper15.CreateFromDiscriminatorValue); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "customer_ip_address", n => { CustomerIpAddress = n.GetStringValue(); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponseDetails>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewResponseDetails.CreateFromDiscriminatorValue); } },
                { "discount_id", n => { DiscountId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview>("address", Address);
            writer.WriteStringValue("address_id", AddressId);
            writer.WriteStringValue("business_id", BusinessId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodeWrapper15>("currency_code", CurrencyCode);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteStringValue("customer_ip_address", CustomerIpAddress);
            writer.WriteStringValue("discount_id", DiscountId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
