// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Calculated totals for a transaction, including proration, discounts, tax, and currency conversion. Considered the source of truth for totals on a transaction.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Breakdown of the payout total for a transaction after adjustments. `null` until the transaction is `completed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted? AdjustedPayoutTotals { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted AdjustedPayoutTotals { get; set; }
#endif
        /// <summary>Breakdown of the totals for a transaction after adjustments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotalsAdjusted? AdjustedTotals { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotalsAdjusted AdjustedTotals { get; private set; }
#endif
        /// <summary>Information about line items for this transaction. Different from transaction `items` as they include totals calculated by Paddle. Considered the source of truth for line item totals.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsLineItem>? LineItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsLineItem> LineItems { get; set; }
#endif
        /// <summary>Breakdown of the payout total for a transaction. `null` until the transaction is `completed`. Returned in your payout currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotals? PayoutTotals { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotals PayoutTotals { get; set; }
#endif
        /// <summary>List of tax rates applied for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsTaxRatesUsedItem>? TaxRatesUsed { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsTaxRatesUsedItem> TaxRatesUsed { get; private set; }
#endif
        /// <summary>Breakdown of the total for a transaction. These numbers can be negative when dealing with subscription updates that result in credit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotals? Totals { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotals Totals { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetails"/> and sets the default values.
        /// </summary>
        public TransactionDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adjusted_payout_totals", n => { AdjustedPayoutTotals = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted.CreateFromDiscriminatorValue); } },
                { "adjusted_totals", n => { AdjustedTotals = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotalsAdjusted>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotalsAdjusted.CreateFromDiscriminatorValue); } },
                { "line_items", n => { LineItems = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsLineItem>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsLineItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "payout_totals", n => { PayoutTotals = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotals>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotals.CreateFromDiscriminatorValue); } },
                { "tax_rates_used", n => { TaxRatesUsed = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsTaxRatesUsedItem>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsTaxRatesUsedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totals", n => { Totals = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotals>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotals.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted>("adjusted_payout_totals", AdjustedPayoutTotals);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionDetailsLineItem>("line_items", LineItems);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotals>("payout_totals", PayoutTotals);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionTotals>("totals", Totals);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
