// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// New or changed entity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionPastDueRequestData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Paddle ID of the address that this transaction is for, prefixed with `add_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressId { get; set; }
#nullable restore
#else
        public string AddressId { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this transaction was marked as `billed`. `null` for transactions that aren&apos;t `billed` or `completed`. Set automatically by Paddle.</summary>
        public DateTimeOffset? BilledAt { get; set; }
        /// <summary>Details for invoicing. Required if `collection_mode` is `manual`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingDetails? BillingDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingDetails BillingDetails { get; set; }
#endif
        /// <summary>Time period that this transaction is for. Set automatically by Paddle for subscription renewals to describe the period that charges are for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingPeriod? BillingPeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingPeriod BillingPeriod { get; set; }
#endif
        /// <summary>Paddle ID of the business that this transaction is for, prefixed with `biz_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessId { get; set; }
#nullable restore
#else
        public string BusinessId { get; set; }
#endif
        /// <summary>Paddle Checkout details for this transaction. Returned for automatically-collected transactions and where `billing_details.enable_checkout` is `true` for manually-collected transactions; `null` otherwise.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCheckout? Checkout { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCheckout Checkout { get; set; }
#endif
        /// <summary>How payment is collected for this transaction. `automatic` for checkout, `manual` for invoices.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCollectionMode? CollectionMode { get; set; }
        /// <summary>RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Supported three-letter ISO 4217 currency code. Must be `USD`, `EUR`, or `GBP` if `collection_mode` is `manual`.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCurrencyCode? CurrencyCode { get; set; }
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCustomData? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCustomData CustomData { get; set; }
#endif
        /// <summary>Paddle ID of the customer that this transaction is for, prefixed with `ctm_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Calculated totals for a transaction, including proration, discounts, tax, and currency conversion. Considered the source of truth for totals on a transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataDetails? Details { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataDetails Details { get; set; }
#endif
        /// <summary>Paddle ID of the discount applied to this transaction, prefixed with `dsc_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscountId { get; set; }
#nullable restore
#else
        public string DiscountId { get; set; }
#endif
        /// <summary>Unique Paddle ID for this transaction entity, prefixed with `txn_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Paddle ID of the invoice that this transaction is related to, prefixed with `inv_`. Used for compatibility with the Paddle Invoice API, which is now deprecated. This field is scheduled to be removed in the next version of the Paddle API.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceId { get; set; }
#nullable restore
#else
        public string InvoiceId { get; set; }
#endif
        /// <summary>Invoice number for this transaction. Automatically generated by Paddle when you mark a transaction as `billed` where `collection_mode` is `manual`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNumber { get; set; }
#nullable restore
#else
        public string InvoiceNumber { get; set; }
#endif
        /// <summary>List of items on this transaction. For calculated totals, use `details.line_items`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataItemsItem>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataItemsItem> Items { get; set; }
#endif
        /// <summary>Describes how this transaction was created.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataOriginOneOf1? Origin { get; set; }
        /// <summary>List of payment attempts for this transaction, including successful payments. Sorted by `created_at` in descending order, so most recent attempts are returned first.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataPaymentsItem>? Payments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataPaymentsItem> Payments { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when a transaction was revised. Revisions describe an update to customer information for a billed or completed transaction. `null` if not revised. Set automatically by Paddle.</summary>
        public DateTimeOffset? RevisedAt { get; set; }
        /// <summary>Status of this transaction. You may set a transaction to `billed` or `canceled`, other statuses are set automatically by Paddle. Automatically-collected transactions may return `completed` if payment is captured successfully, or `past_due` if payment failed.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataStatus? Status { get; set; }
        /// <summary>Paddle ID of the subscription that this transaction is for, prefixed with `sub_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionId { get; set; }
#nullable restore
#else
        public string SubscriptionId { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestData"/> and sets the default values.
        /// </summary>
        public TransactionPastDueRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_id", n => { AddressId = n.GetStringValue(); } },
                { "billed_at", n => { BilledAt = n.GetDateTimeOffsetValue(); } },
                { "billing_details", n => { BillingDetails = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingDetails>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingDetails.CreateFromDiscriminatorValue); } },
                { "billing_period", n => { BillingPeriod = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingPeriod>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingPeriod.CreateFromDiscriminatorValue); } },
                { "business_id", n => { BusinessId = n.GetStringValue(); } },
                { "checkout", n => { Checkout = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCheckout>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCheckout.CreateFromDiscriminatorValue); } },
                { "collection_mode", n => { CollectionMode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCollectionMode>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency_code", n => { CurrencyCode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCurrencyCode>(); } },
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCustomData>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCustomData.CreateFromDiscriminatorValue); } },
                { "customer_id", n => { CustomerId = n.GetStringValue(); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataDetails>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataDetails.CreateFromDiscriminatorValue); } },
                { "discount_id", n => { DiscountId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "invoice_id", n => { InvoiceId = n.GetStringValue(); } },
                { "invoice_number", n => { InvoiceNumber = n.GetStringValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataItemsItem>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataItemsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "origin", n => { Origin = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataOriginOneOf1>(); } },
                { "payments", n => { Payments = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataPaymentsItem>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataPaymentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "revised_at", n => { RevisedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataStatus>(); } },
                { "subscription_id", n => { SubscriptionId = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address_id", AddressId);
            writer.WriteDateTimeOffsetValue("billed_at", BilledAt);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingDetails>("billing_details", BillingDetails);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataBillingPeriod>("billing_period", BillingPeriod);
            writer.WriteStringValue("business_id", BusinessId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCheckout>("checkout", Checkout);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCollectionMode>("collection_mode", CollectionMode);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCurrencyCode>("currency_code", CurrencyCode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataCustomData>("custom_data", CustomData);
            writer.WriteStringValue("customer_id", CustomerId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataDetails>("details", Details);
            writer.WriteStringValue("discount_id", DiscountId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("invoice_id", InvoiceId);
            writer.WriteStringValue("invoice_number", InvoiceNumber);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataItemsItem>("items", Items);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataOriginOneOf1>("origin", Origin);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataPaymentsItem>("payments", Payments);
            writer.WriteDateTimeOffsetValue("revised_at", RevisedAt);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPastDueRequestDataStatus>("status", Status);
            writer.WriteStringValue("subscription_id", SubscriptionId);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
