// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a customer information revision for a transaction.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionRevise : IParsable
    {
        /// <summary>Revised address information for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_address? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_address Address { get; set; }
#endif
        /// <summary>Revised business information for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_business? Business { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_business Business { get; set; }
#endif
        /// <summary>Revised customer information for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_customer? Customer { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_customer Customer { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_address>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_address.CreateFromDiscriminatorValue); } },
                { "business", n => { Business = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_business>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_business.CreateFromDiscriminatorValue); } },
                { "customer", n => { Customer = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_customer>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_customer.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_address>("address", Address);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_business>("business", Business);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionRevise_customer>("customer", Customer);
        }
    }
}
#pragma warning restore CS0618
