// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceAndProductRequest"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceIdRequest"/>, <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceRequest"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionPreviewCreateItems : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceAndProductRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceAndProductRequest? TransactionPreviewItemWithPriceAndProductRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceAndProductRequest TransactionPreviewItemWithPriceAndProductRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceIdRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceIdRequest? TransactionPreviewItemWithPriceIdRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceIdRequest TransactionPreviewItemWithPriceIdRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceRequest? TransactionPreviewItemWithPriceRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceRequest TransactionPreviewItemWithPriceRequest { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewCreateItems"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewCreateItems CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewCreateItems();
            if("TransactionPreviewItemWithPriceAndProductRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TransactionPreviewItemWithPriceAndProductRequest = new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceAndProductRequest();
            }
            else if("TransactionPreviewItemWithPriceIdRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TransactionPreviewItemWithPriceIdRequest = new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceIdRequest();
            }
            else if("TransactionPreviewItemWithPriceRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TransactionPreviewItemWithPriceRequest = new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(TransactionPreviewItemWithPriceAndProductRequest != null)
            {
                return TransactionPreviewItemWithPriceAndProductRequest.GetFieldDeserializers();
            }
            else if(TransactionPreviewItemWithPriceIdRequest != null)
            {
                return TransactionPreviewItemWithPriceIdRequest.GetFieldDeserializers();
            }
            else if(TransactionPreviewItemWithPriceRequest != null)
            {
                return TransactionPreviewItemWithPriceRequest.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(TransactionPreviewItemWithPriceAndProductRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceAndProductRequest>(null, TransactionPreviewItemWithPriceAndProductRequest);
            }
            else if(TransactionPreviewItemWithPriceIdRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceIdRequest>(null, TransactionPreviewItemWithPriceIdRequest);
            }
            else if(TransactionPreviewItemWithPriceRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItemWithPriceRequest>(null, TransactionPreviewItemWithPriceRequest);
            }
        }
    }
}
#pragma warning restore CS0618
