// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Related price entity for this preview line item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionPricingPreviewLineItemPrice : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>How often this price should be charged. `null` if price is non-recurring (one-time).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceBillingCycle? BillingCycle { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceBillingCycle BillingCycle { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Your own structured key-value data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceCustomData? CustomData { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceCustomData CustomData { get; set; }
#endif
        /// <summary>Internal description for this price, not shown to customers. Typically notes for your team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Unique Paddle ID for this price, prefixed with `pri_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Import information for this entity. `null` if this entity is not imported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceImportMeta? ImportMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceImportMeta ImportMeta { get; set; }
#endif
        /// <summary>Name of this price, shown to customers at checkout and on invoices. Typically describes how often the related product bills.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Unique Paddle ID for this product, prefixed with `pro_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>Limits on how many times the related product can be purchased at this price. Useful for discount campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceQuantityComposed? Quantity { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceQuantityComposed Quantity { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceStatus? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceStatus Status { get; set; }
#endif
        /// <summary>The tax_mode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceTaxMode? TaxMode { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceTaxMode TaxMode { get; set; }
#endif
        /// <summary>Trial period for the product related to this price. The billing cycle begins once the trial period is over. `null` for no trial period. Requires `billing_cycle`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceTrialPeriod? TrialPeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceTrialPeriod TrialPeriod { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceType? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceType Type { get; set; }
#endif
        /// <summary>Base price. This price applies to all customers, except for customers located in countries where you have `unit_price_overrides`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceUnitPrice? UnitPrice { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.PriceUnitPrice UnitPrice { get; set; }
#endif
        /// <summary>List of unit price overrides. Use to override the base price with a custom price and currency for a country or group of countries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.UnitPriceOverride>? UnitPriceOverrides { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.UnitPriceOverride> UnitPriceOverrides { get; set; }
#endif
        /// <summary>RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewLineItemPrice"/> and sets the default values.
        /// </summary>
        public TransactionPricingPreviewLineItemPrice()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewLineItemPrice"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewLineItemPrice CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPricingPreviewLineItemPrice();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_cycle", n => { BillingCycle = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceBillingCycle>(global::Soenneker.Paddle.OpenApiClient.Models.PriceBillingCycle.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "custom_data", n => { CustomData = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceCustomData>(global::Soenneker.Paddle.OpenApiClient.Models.PriceCustomData.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "import_meta", n => { ImportMeta = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceImportMeta>(global::Soenneker.Paddle.OpenApiClient.Models.PriceImportMeta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "product_id", n => { ProductId = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceQuantityComposed>(global::Soenneker.Paddle.OpenApiClient.Models.PriceQuantityComposed.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceStatus>(global::Soenneker.Paddle.OpenApiClient.Models.PriceStatus.CreateFromDiscriminatorValue); } },
                { "tax_mode", n => { TaxMode = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceTaxMode>(global::Soenneker.Paddle.OpenApiClient.Models.PriceTaxMode.CreateFromDiscriminatorValue); } },
                { "trial_period", n => { TrialPeriod = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceTrialPeriod>(global::Soenneker.Paddle.OpenApiClient.Models.PriceTrialPeriod.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceType>(global::Soenneker.Paddle.OpenApiClient.Models.PriceType.CreateFromDiscriminatorValue); } },
                { "unit_price", n => { UnitPrice = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceUnitPrice>(global::Soenneker.Paddle.OpenApiClient.Models.PriceUnitPrice.CreateFromDiscriminatorValue); } },
                { "unit_price_overrides", n => { UnitPriceOverrides = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.UnitPriceOverride>(global::Soenneker.Paddle.OpenApiClient.Models.UnitPriceOverride.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceBillingCycle>("billing_cycle", BillingCycle);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceCustomData>("custom_data", CustomData);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceImportMeta>("import_meta", ImportMeta);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("product_id", ProductId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceQuantityComposed>("quantity", Quantity);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceStatus>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceTaxMode>("tax_mode", TaxMode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceTrialPeriod>("trial_period", TrialPeriod);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.PriceUnitPrice>("unit_price", UnitPrice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.UnitPriceOverride>("unit_price_overrides", UnitPriceOverrides);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
