// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Represents a transaction entity when previewing transactions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionPreview : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Address for this transaction preview. Send one of `address_id`, `customer_ip_address`, or the `address` object when previewing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview Address { get; set; }
#endif
        /// <summary>Paddle ID of the address that this transaction preview is for, prefixed with `add_`. Send one of `address_id`, `customer_ip_address`, or the `address` object when previewing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressId? AddressId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.AddressId AddressId { get; set; }
#endif
        /// <summary>List of available payment methods for Paddle Checkout given the price and location information passed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodType?>? AvailablePaymentMethods { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodType?> AvailablePaymentMethods { get; private set; }
#endif
        /// <summary>Paddle ID of the business that this transaction preview is for, prefixed with `biz_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessId? BusinessId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.BusinessId BusinessId { get; set; }
#endif
        /// <summary>Supported three-letter ISO 4217 currency code.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCode? CurrencyCode { get; set; }
        /// <summary>Paddle ID of the customer that this transaction preview is for, prefixed with `ctm_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerId? CustomerId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.CustomerId CustomerId { get; set; }
#endif
        /// <summary>IP address for this transaction preview. Send one of `address_id`, `customer_ip_address`, or the `address` object when previewing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address? CustomerIpAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address CustomerIpAddress { get; set; }
#endif
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewDetails? Details { get; private set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewDetails Details { get; private set; }
#endif
        /// <summary>Paddle ID of the discount applied to this transaction preview, prefixed with `dsc_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountId? DiscountId { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.DiscountId DiscountId { get; set; }
#endif
        /// <summary>Whether trials should be ignored for transaction preview calculations.By default, recurring items with trials are considered to have a zero charge when previewing. Set to `true` to disable this.</summary>
        public bool? IgnoreTrials { get; set; }
        /// <summary>List of items to preview transaction calculations for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItem>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItem> Items { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview"/> and sets the default values.
        /// </summary>
        public TransactionPreview()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview>(global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview.CreateFromDiscriminatorValue); } },
                { "address_id", n => { AddressId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressId>(global::Soenneker.Paddle.OpenApiClient.Models.AddressId.CreateFromDiscriminatorValue); } },
                { "available_payment_methods", n => { AvailablePaymentMethods = n.GetCollectionOfEnumValues<global::Soenneker.Paddle.OpenApiClient.Models.PaymentMethodType>()?.AsList(); } },
                { "business_id", n => { BusinessId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessId>(global::Soenneker.Paddle.OpenApiClient.Models.BusinessId.CreateFromDiscriminatorValue); } },
                { "currency_code", n => { CurrencyCode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCode>(); } },
                { "customer_id", n => { CustomerId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomerId>(global::Soenneker.Paddle.OpenApiClient.Models.CustomerId.CreateFromDiscriminatorValue); } },
                { "customer_ip_address", n => { CustomerIpAddress = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address.CreateFromDiscriminatorValue); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewDetails>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewDetails.CreateFromDiscriminatorValue); } },
                { "discount_id", n => { DiscountId = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountId>(global::Soenneker.Paddle.OpenApiClient.Models.DiscountId.CreateFromDiscriminatorValue); } },
                { "ignore_trials", n => { IgnoreTrials = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItem>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressPreview>("address", Address);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.AddressId>("address_id", AddressId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.BusinessId>("business_id", BusinessId);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCode>("currency_code", CurrencyCode);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.CustomerId>("customer_id", CustomerId);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address>("customer_ip_address", CustomerIpAddress);
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.DiscountId>("discount_id", DiscountId);
            writer.WriteBoolValue("ignore_trials", IgnoreTrials);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreviewItem>("items", Items);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview_customer_ip_addressMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TransactionPreview_customer_ip_address : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview_customer_ip_addressMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview_customer_ip_addressMember1? TransactionPreviewCustomerIpAddressMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview_customer_ip_addressMember1 TransactionPreviewCustomerIpAddressMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview.TransactionPreview_customer_ip_address();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.TransactionPreviewCustomerIpAddressMember1 = new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview_customer_ip_addressMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TransactionPreviewCustomerIpAddressMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TransactionPreviewCustomerIpAddressMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPreview_customer_ip_addressMember1>(null, TransactionPreviewCustomerIpAddressMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
