// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Paddle.OpenApiClient.Models
{
    /// <summary>
    /// Breakdown of the payout total for a transaction after adjustments. `null` until the transaction is `completed`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionPayoutTotalsAdjusted : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Details of any chargeback fees incurred for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjustedChargebackFee? ChargebackFee { get; set; }
#nullable restore
#else
        public global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjustedChargebackFee ChargebackFee { get; set; }
#endif
        /// <summary>Three-letter ISO 4217 currency code used for the payout for this transaction. If your primary currency has changed, this reflects the primary currency at the time the transaction was billed.</summary>
        public global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodePayout? CurrencyCode { get; set; }
        /// <summary>Total earnings for this payout. This is the subtotal minus the Paddle fee, excluding chargeback fees.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Earnings { get; set; }
#nullable restore
#else
        public string Earnings { get; set; }
#endif
        /// <summary>Currency exchange rate, including margin if applicable. `1.0` if the transaction currency matches your payout currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeRate { get; set; }
#nullable restore
#else
        public string ExchangeRate { get; set; }
#endif
        /// <summary>Total fee taken by Paddle for this payout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fee { get; set; }
#nullable restore
#else
        public string Fee { get; set; }
#endif
        /// <summary>Paddle fees retained for this adjustment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RetainedFee { get; private set; }
#nullable restore
#else
        public string RetainedFee { get; private set; }
#endif
        /// <summary>Total before tax and fees.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subtotal { get; set; }
#nullable restore
#else
        public string Subtotal { get; set; }
#endif
        /// <summary>Total tax on the subtotal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tax { get; set; }
#nullable restore
#else
        public string Tax { get; set; }
#endif
        /// <summary>Total after tax.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Total { get; set; }
#nullable restore
#else
        public string Total { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted"/> and sets the default values.
        /// </summary>
        public TransactionPayoutTotalsAdjusted()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjusted();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chargeback_fee", n => { ChargebackFee = n.GetObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjustedChargebackFee>(global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjustedChargebackFee.CreateFromDiscriminatorValue); } },
                { "currency_code", n => { CurrencyCode = n.GetEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodePayout>(); } },
                { "earnings", n => { Earnings = n.GetStringValue(); } },
                { "exchange_rate", n => { ExchangeRate = n.GetStringValue(); } },
                { "fee", n => { Fee = n.GetStringValue(); } },
                { "retained_fee", n => { RetainedFee = n.GetStringValue(); } },
                { "subtotal", n => { Subtotal = n.GetStringValue(); } },
                { "tax", n => { Tax = n.GetStringValue(); } },
                { "total", n => { Total = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Paddle.OpenApiClient.Models.TransactionPayoutTotalsAdjustedChargebackFee>("chargeback_fee", ChargebackFee);
            writer.WriteEnumValue<global::Soenneker.Paddle.OpenApiClient.Models.CurrencyCodePayout>("currency_code", CurrencyCode);
            writer.WriteStringValue("earnings", Earnings);
            writer.WriteStringValue("exchange_rate", ExchangeRate);
            writer.WriteStringValue("fee", Fee);
            writer.WriteStringValue("subtotal", Subtotal);
            writer.WriteStringValue("tax", Tax);
            writer.WriteStringValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
