// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Paddle.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Paddle.OpenApiClient.Discounts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \discounts\{discount_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDiscount_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDiscount_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/discounts/{discount_id}{?include}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDiscount_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/discounts/{discount_id}{?include}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a discount using its ID.
        /// Get a discount <see href="https://developer.paddle.com/api-reference/discounts/get-discount" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_GetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder.WithDiscount_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_GetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder.WithDiscount_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_GetResponse>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a discount using its ID.If successful, your response includes a copy of the updated discount entity.To update a checkout recovery discount, configure your checkout recovery settings in the dashboard.
        /// Update a discount <see href="https://developer.paddle.com/api-reference/discounts/update-discount" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_PatchResponse"/></returns>
        /// <param name="body">Represents a discount entity when updating discounts.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_PatchResponse?> PatchAsync(global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_PatchResponse> PatchAsync(global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_PatchResponse>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_PatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a discount using its ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder.WithDiscount_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder.WithDiscount_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates a discount using its ID.If successful, your response includes a copy of the updated discount entity.To update a checkout recovery discount, configure your checkout recovery settings in the dashboard.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Represents a discount entity when updating discounts.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Paddle.OpenApiClient.Models.DiscountUpdate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Paddle.OpenApiClient.Discounts.Item.WithDiscount_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a discount using its ID.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDiscount_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Include related entities in the response. Use a comma-separated list to specify multiple entities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public global::Soenneker.Paddle.OpenApiClient.Models.DiscountIncludeEnum[]? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public global::Soenneker.Paddle.OpenApiClient.Models.DiscountIncludeEnum[] Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
