// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Paddle.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Paddle.OpenApiClient.Products.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \products\{productId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProductItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "", rawUrl)
        {
        }
        /// <summary>
        /// Returns a product using its ID.Use the `include` parameter to include related price entities in the response.
        /// Get a product <see href="https://developer.paddle.com/api-reference/products/get-product" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.GetProduct200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Models.GetProduct200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder.WithProductItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Models.GetProduct200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder.WithProductItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Models.GetProduct200Response>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Models.GetProduct200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a product using its ID.Paddle does not upload product images to a CDN. For `image_url`, you should host images on an HTTPS server that&apos;s publicly accessible. We recommend using square images (`1:1` ratio).If successful, your response includes a copy of the updated product entity.
        /// Update a product <see href="https://developer.paddle.com/api-reference/products/update-product" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Models.UpdateProduct200Response"/></returns>
        /// <param name="body">Represents a product entity when updating products.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Models.UpdateProduct200Response?> PatchAsync(global::Soenneker.Paddle.OpenApiClient.Models.ProductUpdate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Models.UpdateProduct200Response> PatchAsync(global::Soenneker.Paddle.OpenApiClient.Models.ProductUpdate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Models.UpdateProduct200Response>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Models.UpdateProduct200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a product using its ID.Use the `include` parameter to include related price entities in the response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder.WithProductItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder.WithProductItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/products/{productId}{?include}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates a product using its ID.Paddle does not upload product images to a CDN. For `image_url`, you should host images on an HTTPS server that&apos;s publicly accessible. We recommend using square images (`1:1` ratio).If successful, your response includes a copy of the updated product entity.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Represents a product entity when updating products.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Paddle.OpenApiClient.Models.ProductUpdate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Paddle.OpenApiClient.Models.ProductUpdate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, "{+baseurl}/products/{productId}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Paddle.OpenApiClient.Products.Item.WithProductItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a product using its ID.Use the `include` parameter to include related price entities in the response.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProductItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Include related entities in the response. Use a comma-separated list to specify multiple entities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public global::Soenneker.Paddle.OpenApiClient.Models.ProductIncludeEnum[]? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public global::Soenneker.Paddle.OpenApiClient.Models.ProductIncludeEnum[] Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
