// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Paddle.OpenApiClient.Models;
using Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.Events;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \simulations\{simulation_id}\runs\{simulation_run_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSimulation_run_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The events property</summary>
        public global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSimulation_run_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/simulations/{simulation_id}/runs/{simulation_run_id}{?include}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSimulation_run_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/simulations/{simulation_id}/runs/{simulation_run_id}{?include}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a simulation run using its ID.Use the `include` parameter to include related entities in the response.
        /// Get a run for a simulation <see href="https://developer.paddle.com/api-reference/simulation-runs/get-simulation-run" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_GetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder.WithSimulation_run_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_GetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder.WithSimulation_run_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_GetResponse>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a simulation run using its ID.Use the `include` parameter to include related entities in the response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder.WithSimulation_run_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder.WithSimulation_run_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Paddle.OpenApiClient.Simulations.Item.Runs.Item.WithSimulation_run_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a simulation run using its ID.Use the `include` parameter to include related entities in the response.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSimulation_run_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Include related entities in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public global::Soenneker.Paddle.OpenApiClient.Models.SimulationsRunIncludeEnum[]? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public global::Soenneker.Paddle.OpenApiClient.Models.SimulationsRunIncludeEnum[] Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
