// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.Item;
using Soenneker.Paddle.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses
{
    /// <summary>
    /// Builds and executes requests for operations under \customers\{customer_id}\businesses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Paddle.OpenApiClient.customers.item.businesses.item collection</summary>
        /// <param name="position">Paddle ID of the business entity to work with.</param>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.Item.WithBusiness_ItemRequestBuilder"/></returns>
        public global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.Item.WithBusiness_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("business_id", position);
                return new global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.Item.WithBusiness_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BusinessesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customers/{customer_id}/businesses{?after,id,order_by,per_page,search,status}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BusinessesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customers/{customer_id}/businesses{?after,id,order_by,per_page,search,status}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a paginated list of businesses for a customer. Use the query parameters to page through results.By default, Paddle returns businesses that are `active`. Use the `status` query parameter to return businesses that are archived.
        /// List businesses for a customer <see href="https://developer.paddle.com/api-reference/businesses/list-businesses" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder.BusinessesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder.BusinessesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesGetResponse>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new business for a customer.If successful, your response includes a copy of the new business entity.
        /// Create a business for a customer <see href="https://developer.paddle.com/api-reference/businesses/create-business" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesPostResponse"/></returns>
        /// <param name="body">Represents a business entity when creating businesses.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesPostResponse?> PostAsync(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesPostResponse> PostAsync(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Paddle.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesPostResponse>(requestInfo, global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a paginated list of businesses for a customer. Use the query parameters to page through results.By default, Paddle returns businesses that are `active`. Use the `status` query parameter to return businesses that are archived.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder.BusinessesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder.BusinessesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new business for a customer.If successful, your response includes a copy of the new business entity.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Represents a business entity when creating businesses.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Paddle.OpenApiClient.Models.BusinessCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Paddle.OpenApiClient.Customers.Item.Businesses.BusinessesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a paginated list of businesses for a customer. Use the query parameters to page through results.By default, Paddle returns businesses that are `active`. Use the `status` query parameter to return businesses that are archived.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BusinessesRequestBuilderGetQueryParameters 
        {
            /// <summary>Return entities after the specified Paddle ID when working with paginated endpoints. Used in the `meta.pagination.next` URL in responses for list operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after")]
            public string? After { get; set; }
#nullable restore
#else
            [QueryParameter("after")]
            public string After { get; set; }
#endif
            /// <summary>Return only the IDs specified. Use a comma-separated list to get multiple entities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public string[]? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public string[] Id { get; set; }
#endif
            /// <summary>Order returned entities by the specified field and direction (`[ASC]` or `[DESC]`). For example, `?order_by=id[ASC]`.Valid fields for ordering: `id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_by")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("order_by")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Set how many entities are returned per page. Paddle returns the maximum number of results if a number greater than the maximum is requested. Check `meta.pagination.per_page` in the response to see how many were returned.Default: `50`; Maximum: `200`.</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>Return entities that match a search query. Searches all fields, including contacts, except `status`, `created_at`, and `updated_at`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Return entities that match the specified status. Use a comma-separated list to specify multiple status values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public global::Soenneker.Paddle.OpenApiClient.Models.StatusQuery[]? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public global::Soenneker.Paddle.OpenApiClient.Models.StatusQuery[] Status { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
